### ISSUE TITLE
Swedish page shows Swedish street marker but Finnish base map

### ISSUE THREAD

**Issue by hugovk** [City-of-Helsinki/outdoors-sports-map#50]
## Steps to reproduce:
1. Go to https://ulkoliikunta.fi/
2. Click Swedish in the top right
3. Check the names on the map

## Expected result:
The base map shows Swedish names, like the street name marker in the top left.

## Actual result:
The base map shows Finnish names, but the street name marker in the top left is Swedish.

![image](https://cloud.githubusercontent.com/assets/1324225/24907834/766a2fae-1ec6-11e7-9afc-116b76eaabb3.png)

## More info
The map and marker is Finnish for Finnish, as expected.

**Comment by Jokinen** [comment]
Thank you for reporting the issue! I've added into our issue tracker: https://helsinkisolutionoffice.atlassian.net/browse/ULK-141

**Comment by Jokinen** [comment]
This should have been fixed in [1.2.0](https://github.com/City-of-Helsinki/outdoors-sports-map/releases/tag/release-1.2.0)

**Comment by hugovk** [comment]
Confirmed, thank you!

(New issue: using [flags](http://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/) to [represent](https://uxdesign.cc/my-take-on-language-selectors-945caceb58f7) [languages](https://jkorpela.fi/flags.html) is [discouraged](https://wplang.org/never-use-flags-language-selection/).)

# FI

![image](https://user-images.githubusercontent.com/1324225/123064264-cab28c00-d416-11eb-8302-e58c939c36d1.png)

![image](https://user-images.githubusercontent.com/1324225/123065281-b15e0f80-d417-11eb-90a0-5c84dfdd3645.png)


# SV

![image](https://user-images.githubusercontent.com/1324225/123064324-d900a800-d416-11eb-9dcb-578e3a4e4c49.png)

![image](https://user-images.githubusercontent.com/1324225/123065318-b91db400-d417-11eb-8e42-ce08ccc3d9fb.png)

# EN

![image](https://user-images.githubusercontent.com/1324225/123064351-df8f1f80-d416-11eb-9fda-ba6852f87d0e.png)

![image](https://user-images.githubusercontent.com/1324225/123065359-c0dd5880-d417-11eb-9723-5d4fe0d722d8.png)

**Comment by Jokinen** [comment]
Thank you for the comment @hugovk 

The usage of flags was briefly discussed during the design phase. However, I'll forward this concern and the resources you provided so that we can reassess whether we made compromises we were not aware about.

**Comment by Jokinen** [comment]
Due to our current circumstances and the ongoing vacation season, we do not have enough resources to provide a definitive answer right away.

We have documented this concern in our issue tracker so that it can be looked at again at a later date. Unfortunately I can't provide you with a timeframe with any certainty. In the best case scenario, it's unlikely that we will be able to take this on before fall.

https://helsinkisolutionoffice.atlassian.net/browse/ULK-153

**Comment by hugovk** [comment]
Thank you, hope you all have a nice summer!
