### ISSUE TITLE
Wrong links to Github

### ISSUE THREAD

**Issue by posikifi** [City-of-Helsinki/outdoors-sports-map#62]
Current site (ulkoliikunta.fi) has wrong links to Github repository.

It seems to be https://github.com/nordsoftware/outdoors-sports-map, but forwards to https://github.com/digiaonline/outdoors-sports-map which is outdates.

Please fix links.

**Comment by Jokinen** [comment]
Thank you for reporting the issue!

The links were fixed in release [1.1.6](https://github.com/City-of-Helsinki/outdoors-sports-map/releases/tag/release-1.1.6)
