### ISSUE TITLE
Feedback form is not working

### ISSUE THREAD

**Issue by posikifi** [City-of-Helsinki/outdoors-sports-map#63]
Feedback form's text and email inputs are not working

![Ulkoliikunta_palaute](https://user-images.githubusercontent.com/1785962/104839925-0fb51e00-58cd-11eb-8c95-02e6b4d727df.png)

**Comment by posikifi** [comment]
It seems that feedback form is not working when ski track is selectect. If not any items selected, forms seem to work as designed. I presume

**Comment by Jokinen** [comment]
Thank you for reporting the issue! I've added it into our issue tracker: https://helsinkisolutionoffice.atlassian.net/browse/ULK-142

**Comment by Jokinen** [comment]
We made changes to providing feedback, including a bugfix that would sometimes cause feedback sending to fail.

I attempted to reproduce this issue with the new and old versions, but I could not. Please reopen this issue if the problem has persisted.
