### ISSUE TITLE
Location of REST api

### ISSUE THREAD

**Issue by posikifi** [City-of-Helsinki/outdoors-sports-map#64]
Info window told: "Liikuntapaikkojen tiedot ovat avointa dataa ja käytettävissä REST-rajapinnan kautta."

Where is REST API?

**Comment by jhiltula** [comment]
I'd like to know the same

**Comment by Jokinen** [comment]
Thank you for the question. The service uses the "Service Map" API. You can read more about it here: https://dev.hel.fi/apis/service-map-backend-api

**Comment by Jokinen** [comment]
If you want to know more or would like to suggest other changes, please reopen the issue.

I will close it for now as the question itself was answered.
