### ISSUE TITLE
Feedback form: text box badly defined

### ISSUE THREAD

**Issue by posikifi** [City-of-Helsinki/outdoors-sports-map#65]
When you resize text of feedback form, result is pretty ackward (IMHO).

![Ulkoliikunta_palaute](https://user-images.githubusercontent.com/1785962/104843488-979e2680-58d3-11eb-8e1e-af939b7ed460.png)

**Comment by Jokinen** [comment]
Thank you for your feedback!

You are correct, the behaviour is awkward. I'll find out how we can track this issue.

**Comment by Jokinen** [comment]
This should be resolved in version [1.2.0](https://github.com/City-of-Helsinki/outdoors-sports-map/releases/tag/release-1.2.0)

We changed the modal implementation and this styling issue was fixed at the same time.
